package migraciones

import (
	"strings"
	"testing"
)

// Escribir `migrations_dialect: postgres` a ciegas dejó de ser gratis en el
// momento en que `init` empezó a rellenar paths.migrations de verdad.
//
// Antes, un repo SQLite acababa con la lista VACÍA y squawk no corría nunca:
// sin cobertura, en silencio. Ahora la lista se llena, y con el dialecto
// equivocado squawk —que sólo entiende PostgreSQL— bloquea el primer commit de
// esquema. Medido: un `CREATE INDEX` perfectamente legal en SQLite salió
// BLOQUEADO exigiendo CONCURRENTLY, sintaxis que en SQLite NO EXISTE. El dev se
// queda sin salida: el consejo es imposible de seguir.
//
// Así que se deduce del propio DDL, y sólo con pruebas positivas.
func TestElDialectoSeDeduceDelDDLYNoSeAsume(t *testing.T) {
	for _, c := range []struct {
		nombre, ddl, quiero string
	}{
		{
			"SQLite por AUTOINCREMENT y PRAGMA",
			"PRAGMA foreign_keys = ON;\nCREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT);",
			"sqlite",
		},
		{
			"SQLite por WITHOUT ROWID",
			"CREATE TABLE t (id INTEGER PRIMARY KEY) WITHOUT ROWID;",
			"sqlite",
		},
		{
			"MySQL por ENGINE y AUTO_INCREMENT",
			"CREATE TABLE `cuenta` (id INT AUTO_INCREMENT PRIMARY KEY) ENGINE=InnoDB;",
			"mysql",
		},
		{
			"SQL Server por IDENTITY y NVARCHAR",
			"CREATE TABLE cuenta (id INT IDENTITY(1,1), nombre NVARCHAR(50));\nGO\n",
			"sqlserver",
		},
		{
			"PostgreSQL de manual: se queda en el valor por defecto",
			"CREATE TABLE cuenta (id bigserial PRIMARY KEY, datos jsonb);",
			"",
		},
		{
			"DDL sin ninguna marca: NO se inventa nada",
			"CREATE TABLE cuenta (id INTEGER PRIMARY KEY, total REAL NOT NULL);",
			"",
		},
	} {
		t.Run(c.nombre, func(t *testing.T) {
			if got := motorInsinuado([]string{c.ddl}); got != c.quiero {
				t.Errorf("dialecto %q, esperaba %q\nDDL:\n%s", got, c.quiero, c.ddl)
			}
		})
	}
}

// El fallo peor que encontró el validador: UN archivo decidía por el repo
// entero, y lo apagaba en silencio.
//
// Un repo que migró de MySQL a PostgreSQL y conservó el volcado viejo entre sus
// migraciones quedaba marcado como MySQL. Medido: `ALTER TABLE ... DROP COLUMN`
// más `ADD COLUMN ... NOT NULL` sobre una migración PostgreSQL de verdad salió
// con EXIT=0 y el commit se creó —con el binario anterior BLOQUEABA—, y
// `status` lo remataba con "✓ datos mysql · squawk no aplica": un check verde
// sobre migraciones que ya no miraba nadie.
//
// Migrar de motor y conservar el volcado es lo normal, no un caso raro.
func TestUnVolcadoHeredadoSeDistingueDeUnRepoMySQL(t *testing.T) {
	d := Analizar([]string{
		// El legado, con todas las marcas de MySQL.
		"CREATE TABLE `cuenta` (`id` INT AUTO_INCREMENT PRIMARY KEY) ENGINE=InnoDB;",
		// Y las migraciones de verdad, que son PostgreSQL.
		"CREATE TABLE cuenta (id bigserial PRIMARY KEY, datos jsonb);",
		"ALTER TABLE cuenta ADD COLUMN creado timestamptz NOT NULL DEFAULT now();",
	})
	// Se avisa de MySQL, porque hay marcas y callarlas sería esconder algo…
	if len(d.Pistas["mysql"]) != 1 || d.Pistas["mysql"][0] != 0 {
		t.Errorf("la pista de MySQL tiene que quedar con SU archivo (el 0): %+v", d.Pistas)
	}
	// …pero también hay marcas de PostgreSQL en dos archivos, y eso es lo que
	// le permite al dev leer «esto es un volcado heredado» en vez de creerse
	// que su repo es MySQL. Sin las dos mitades, el aviso engaña.
	if len(d.Pistas["postgres"]) != 2 {
		t.Errorf("faltan las pistas de PostgreSQL, que son las que dan contexto: %+v", d.Pistas)
	}
}

// Un repo de un solo motor deja pistas de ese motor y de ningún otro. Es lo que
// hace que el aviso se pueda escribir sin rodeos.
func TestUnRepoDeUnSoloMotorDejaUnaSolaPista(t *testing.T) {
	d := Analizar([]string{
		"PRAGMA foreign_keys = ON;",
		"CREATE TABLE cuenta (id INTEGER PRIMARY KEY AUTOINCREMENT);",
	})
	if otros := d.OtrosMotores(); len(otros) != 1 || otros[0] != "sqlite" {
		t.Errorf("esperaba pistas sólo de sqlite, salieron %v (%+v)", otros, d.Pistas)
	}
	if len(d.Pistas["postgres"]) != 0 {
		t.Errorf("un esquema SQLite no puede dejar pistas de PostgreSQL: %+v", d.Pistas)
	}
}

// Las marcas se buscan en TODOS los archivos, no sólo en el primero.
func TestElDialectoSeBuscaEnTodasLasMigraciones(t *testing.T) {
	got := motorInsinuado([]string{
		"CREATE TABLE a (id INTEGER PRIMARY KEY);\nPRAGMA foreign_keys = ON;",
		"ALTER TABLE a ADD COLUMN x TEXT;\nPRAGMA journal_mode = WAL;",
	})
	if got != "sqlite" {
		t.Errorf("dialecto %q, esperaba sqlite", got)
	}
}

// PostgreSQL MODERNO no deja ninguna huella de las que se buscan —`bigint
// GENERATED BY DEFAULT AS IDENTITY`, `varchar`, `timestamp`—, y ese es
// exactamente el motivo por el que este paquete NO decide.
//
// Cuando decidía, un repo así con un volcado MySQL heredado quedaba marcado
// como MySQL entero: medido, el DROP COLUMN pasaba con EXIT=0 y `status` lo
// daba por bueno. Ninguna heurística arregla eso, porque no hay nada que
// detectar. Lo único que se puede hacer es DECIRLO y dejar que el equipo mire.
func TestElAvisoNombraElArchivoQueLevantoLaSospecha(t *testing.T) {
	d := Analizar([]string{
		"CREATE TABLE cuenta (id bigint GENERATED BY DEFAULT AS IDENTITY, nombre varchar(120));",
		"CREATE TABLE `cuenta` (`id` INT AUTO_INCREMENT PRIMARY KEY) ENGINE=InnoDB;", // el legado
		"ALTER TABLE cuenta ADD COLUMN saldo numeric;",
	})
	idx := d.Pistas["mysql"]
	if len(idx) != 1 || idx[0] != 1 {
		t.Errorf("la pista tiene que apuntar al archivo 1, que es el heredado: %+v", d.Pistas)
	}
	// Nombrar el archivo no es un detalle: un aviso que dice «vi marcas de
	// MySQL» sin decir dónde no se puede comprobar, y lo que no se puede
	// comprobar se acaba ignorando.
	if d.Archivos != 3 {
		t.Errorf("hay que saber sobre cuántos archivos se habla para poder decir «1 de 3»: %d", d.Archivos)
	}
}

// Marcas que existen en OTROS motores y que por tanto no pueden delatar a
// nadie. Cada una de estas volvió a bloquear un repo legítimo cuando estuvo en
// la lista, porque provocaba un conflicto falso.
func TestLasMarcasAmbiguasNoDelatanANadie(t *testing.T) {
	for _, c := range []struct{ nombre, ddl, quiero string }{
		{
			// NVARCHAR(n) es sinónimo de VARCHAR(n) CHARACTER SET utf8 en MySQL.
			"MySQL con NVARCHAR sigue siendo MySQL",
			"CREATE TABLE cliente (`id` INT NOT NULL AUTO_INCREMENT, `nombre` NVARCHAR(50) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;",
			"mysql",
		},
		{
			// jsonb() es función nativa de SQLite desde la 3.45 (2024).
			"SQLite con jsonb() sigue siendo SQLite",
			"CREATE TABLE doc (id INTEGER PRIMARY KEY AUTOINCREMENT, raw TEXT, body BLOB GENERATED ALWAYS AS (jsonb(raw)) STORED);",
			"sqlite",
		},
		{
			// RETURNING existe en MariaDB; USING BTREE es sintaxis de índice MySQL.
			"MariaDB con RETURNING y USING BTREE sigue siendo MySQL",
			"ALTER TABLE `t` ADD INDEX `i` (`c`) USING BTREE;\nINSERT INTO `t` VALUES (1) RETURNING `id`;",
			"mysql",
		},
	} {
		t.Run(c.nombre, func(t *testing.T) {
			if got := motorInsinuado([]string{c.ddl}); got != c.quiero {
				t.Errorf("dialecto %q, esperaba %q: una marca ambigua provoca un "+
					"conflicto falso, y el conflicto devuelve PostgreSQL, que BLOQUEA "+
					"este repo con un consejo que no puede aplicar.\nDDL:\n%s",
					got, c.quiero, c.ddl)
			}
		})
	}
}

// El cuerpo de una función PL/pgSQL va entre $$ y dentro cabe CUALQUIER cosa:
// documentación, SQL de otro motor citado como ejemplo, nombres con acentos
// graves. Es el camino más plausible por el que un repo PostgreSQL de verdad
// se clasificaría mal — y clasificarlo mal le apaga la compuerta EN SILENCIO,
// que es peor que el bloqueo que este detector vino a quitar.
func TestElCuerpoDeUnaFuncionNoDecideElMotor(t *testing.T) {
	// Las marcas van DESNUDAS dentro del $$: ni en un comentario ni entre
	// comillas simples, que son los dos casos que ya se descartaban. Documentar
	// con $$ es justamente lo que se hace para no tener que escapar comillas.
	ddl := "CREATE TABLE cuenta (id bigserial PRIMARY KEY);\n" +
		"COMMENT ON COLUMN cuenta.id IS $$equivale al AUTO_INCREMENT de MySQL; " +
		"en SQLite sería AUTOINCREMENT y la tabla iría con ENGINE=InnoDB$$;"
	if got := motorInsinuado([]string{ddl}); got != "" {
		t.Errorf("dialecto %q sobre un repo PostgreSQL: las marcas venían dentro de un cuerpo $$.\n"+
			"Clasificarlo mal apaga squawk sin decírselo a nadie.", got)
	}
}

// Con etiqueta: $func$ … $func$ es igual de corriente que $$ … $$.
func TestElCuerpoEtiquetadoTampocoDecideElMotor(t *testing.T) {
	ddl := "CREATE FUNCTION f() RETURNS text AS $func$\n" +
		"  SELECT 'ver la versión con ENGINE=InnoDB y AUTO_INCREMENT'::text;\n" +
		"$func$ LANGUAGE sql;\n" +
		"CREATE TABLE t (id bigserial PRIMARY KEY, nota text);\n" +
		"COMMENT ON TABLE t IS $doc$columna id: sin AUTOINCREMENT, aquí es bigserial$doc$;"
	if got := motorInsinuado([]string{ddl}); got != "" {
		t.Errorf("dialecto %q: las marcas venían dentro de un cuerpo $func$", got)
	}
}

// Y el control que impide el arreglo perezoso: si saltar los cuerpos $$ se
// llevara por delante lo que viene DETRÁS, el detector quedaría ciego y nadie
// se enteraría — sólo dejaría de detectar.
//
// Se comprueba sobre el limpiador y no sobre Dialecto() a propósito: mezclar
// aquí un CREATE FUNCTION mediría además la regla del conflicto, y entonces un
// fallo del limpiador podría esconderse detrás de un "" perfectamente legítimo.
func TestSaltarUnCuerpoNoSeLlevaLoQueVieneDetras(t *testing.T) {
	limpio := sinComentariosNiCadenas(
		"CREATE FUNCTION f() RETURNS void AS $$ SELECT 1; $$ LANGUAGE plpgsql;\n" +
			"CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT);")
	for _, quiero := range []string{"CREATE TABLE t", "AUTOINCREMENT"} {
		if !strings.Contains(limpio, quiero) {
			t.Errorf("el limpiador se comió %q junto con el cuerpo $$:\n%s", quiero, limpio)
		}
	}
	if strings.Contains(limpio, "SELECT 1") {
		t.Errorf("el cuerpo $$ tenía que desaparecer:\n%s", limpio)
	}
}

// Un cuerpo $$ sin cerrar no puede tragarse el archivo entero en silencio…
// pero tampoco puede analizarse como si fuera código: se descarta el resto, que
// es la opción que no inventa nada.
func TestUnCuerpoSinCerrarNoRompeElDetector(t *testing.T) {
	if got := motorInsinuado([]string{"CREATE TABLE t (id INTEGER);\nCREATE FUNCTION f() AS $$ sin cerrar"}); got != "" {
		t.Errorf("dialecto %q sobre un archivo truncado: no hay nada que afirmar", got)
	}
}

// Una palabra dentro de un comentario o de una cadena no es una marca. Si lo
// fuera, bastaría documentar "no usamos AUTO_INCREMENT" para que el repo
// entero se clasificara mal y squawk se apagara sin que nadie lo decidiera.
func TestUnaMarcaEnUnComentarioNoCuenta(t *testing.T) {
	ddl := "-- ojo: aquí no usamos AUTO_INCREMENT ni ENGINE=InnoDB\n" +
		"/* tampoco PRAGMA ni AUTOINCREMENT */\n" +
		"CREATE TABLE cuenta (id bigserial PRIMARY KEY);"
	if got := motorInsinuado([]string{ddl}); got != "" {
		t.Errorf("dialecto %q: las marcas venían todas en comentarios", got)
	}
}

// motorInsinuado es el andamio de estas pruebas: reduce las pistas a un solo
// nombre para poder afirmar sobre ellas.
//
// No existe en producción A PROPÓSITO. `init` no elige motor: avisa y deja
// decidir al equipo, porque una detección que falla apaga la compuerta en
// silencio. Aquí se colapsa a un nombre sólo para comprobar que las MARCAS
// distinguen lo que tienen que distinguir.
func motorInsinuado(contenidos []string) string {
	otros := Analizar(contenidos).OtrosMotores()
	if len(otros) == 1 {
		return otros[0]
	}
	if len(otros) > 1 {
		return "conflicto"
	}
	return ""
}
